/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 24.11
 * Usage: Interface to C
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#include "HCHalcon_YouloBe.h"

extern HUserImport int HHalcon_YouloBeGetOffset();

int offset = -1;

Herror HcPreCallUser(int proc_index_local, Hproc_handle *proc_handle)
{
  if (offset < 0)
  {
    /* First use of this extension package, query my offset */
    if (0 > (offset = HHalcon_YouloBeGetOffset()))
    {
      /*
       * Either the HALCON library was not initialized or the extension package
       * was not loaded. Make sure HALCON is initialized and check the offset
       * again.
       */
      Herror err = HcPreCall(-1, proc_handle);
      if (H_MSG_OK != err)
        return err;
      if (0 > (offset = HHalcon_YouloBeGetOffset()))
      {
        /* The extension package could not be loaded. */
        return H_ERR_UEXTNI;
      }
      HcPostCall(*proc_handle, H_MSG_OK);
      *proc_handle = NULL;
    }
  }
  return HcPreCall(offset + proc_index_local, proc_handle);
}

HUserExport Herror T_yolo_seg_detect(const Htuple Handle, const Htuple DictHandle)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(0,&ph);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&Handle);
  if (err == H_MSG_OK) err = HcStoreICT(ph,1,&DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_cv_estimate_affine_partial2d(const Htuple DictHandle)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(1,&ph);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_cv_bf_knn_match(const Htuple DictHandle)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(2,&ph);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_cv_akaze_detect(const Htuple DictHandle)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(3,&ph);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_cv_orb_detect(const Htuple DictHandle)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(4,&ph);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_write_image_exif(const Htuple image_path, const Htuple latitude, const Htuple longitude, const Htuple altitude, const Htuple aperture, const Htuple shutter_speed, const Htuple iso_number, const Htuple focal_length, const Htuple date_time, const Htuple camera_make, const Htuple camera_model)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(5,&ph);
  if (err == H_MSG_OK) err = HcStoreICTEnc(ph,0,&image_path);
  if (err == H_MSG_OK) err = HcStoreICT(ph,1,&latitude);
  if (err == H_MSG_OK) err = HcStoreICT(ph,2,&longitude);
  if (err == H_MSG_OK) err = HcStoreICT(ph,3,&altitude);
  if (err == H_MSG_OK) err = HcStoreICT(ph,4,&aperture);
  if (err == H_MSG_OK) err = HcStoreICT(ph,5,&shutter_speed);
  if (err == H_MSG_OK) err = HcStoreICT(ph,6,&iso_number);
  if (err == H_MSG_OK) err = HcStoreICT(ph,7,&focal_length);
  if (err == H_MSG_OK) err = HcStoreICTEnc(ph,8,&date_time);
  if (err == H_MSG_OK) err = HcStoreICTEnc(ph,9,&camera_make);
  if (err == H_MSG_OK) err = HcStoreICTEnc(ph,10,&camera_model);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_CLAHE_image(const Hobject inimage, Hobject *outimage, const Htuple k_width, const Htuple k_height, const Htuple clipLimit)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(6,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,inimage);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&k_width);
  if (err == H_MSG_OK) err = HcStoreICT(ph,1,&k_height);
  if (err == H_MSG_OK) err = HcStoreICT(ph,2,&clipLimit);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  err = HcStoreOO(ph,1,outimage,err);
  return HcPostCall(ph,err);
}

HUserExport Herror T_sub_A_roi(const Hobject smallimage, const Hobject bigimage, const Htuple sy, const Htuple sx, const Htuple ew, const Htuple eh)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(7,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,smallimage);
  if (err == H_MSG_OK) err = HcStoreIO(ph,2,bigimage);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&sy);
  if (err == H_MSG_OK) err = HcStoreICT(ph,1,&sx);
  if (err == H_MSG_OK) err = HcStoreICT(ph,2,&ew);
  if (err == H_MSG_OK) err = HcStoreICT(ph,3,&eh);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_div_A_roi(const Hobject smallimage, const Hobject bigimage, const Htuple sy, const Htuple sx, const Htuple ew, const Htuple eh)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(8,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,smallimage);
  if (err == H_MSG_OK) err = HcStoreIO(ph,2,bigimage);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&sy);
  if (err == H_MSG_OK) err = HcStoreICT(ph,1,&sx);
  if (err == H_MSG_OK) err = HcStoreICT(ph,2,&ew);
  if (err == H_MSG_OK) err = HcStoreICT(ph,3,&eh);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_div_B_roi(const Hobject smallimage, const Hobject bigimage, const Htuple sy, const Htuple sx, const Htuple ew, const Htuple eh)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(9,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,smallimage);
  if (err == H_MSG_OK) err = HcStoreIO(ph,2,bigimage);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&sy);
  if (err == H_MSG_OK) err = HcStoreICT(ph,1,&sx);
  if (err == H_MSG_OK) err = HcStoreICT(ph,2,&ew);
  if (err == H_MSG_OK) err = HcStoreICT(ph,3,&eh);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_sub_B_roi(const Hobject smallimage, const Hobject bigimage, const Htuple sy, const Htuple sx, const Htuple ew, const Htuple eh)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(10,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,smallimage);
  if (err == H_MSG_OK) err = HcStoreIO(ph,2,bigimage);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&sy);
  if (err == H_MSG_OK) err = HcStoreICT(ph,1,&sx);
  if (err == H_MSG_OK) err = HcStoreICT(ph,2,&ew);
  if (err == H_MSG_OK) err = HcStoreICT(ph,3,&eh);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_mul_roi(const Hobject smallimage, const Hobject bigimage, const Htuple sy, const Htuple sx, const Htuple ew, const Htuple eh)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(11,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,smallimage);
  if (err == H_MSG_OK) err = HcStoreIO(ph,2,bigimage);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&sy);
  if (err == H_MSG_OK) err = HcStoreICT(ph,1,&sx);
  if (err == H_MSG_OK) err = HcStoreICT(ph,2,&ew);
  if (err == H_MSG_OK) err = HcStoreICT(ph,3,&eh);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_add_roi(const Hobject smallimage, const Hobject bigimage, const Htuple sy, const Htuple sx, const Htuple ew, const Htuple eh)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(12,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,smallimage);
  if (err == H_MSG_OK) err = HcStoreIO(ph,2,bigimage);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&sy);
  if (err == H_MSG_OK) err = HcStoreICT(ph,1,&sx);
  if (err == H_MSG_OK) err = HcStoreICT(ph,2,&ew);
  if (err == H_MSG_OK) err = HcStoreICT(ph,3,&eh);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_PNGIn(const Hobject inimage, Hobject *outimage, const Htuple acceleration)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(13,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,inimage);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&acceleration);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  err = HcStoreOO(ph,1,outimage,err);
  return HcPostCall(ph,err);
}

HUserExport Herror T_PNGOut(const Hobject inimage, Hobject *outimage)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(14,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,inimage);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  err = HcStoreOO(ph,1,outimage,err);
  return HcPostCall(ph,err);
}

HUserExport Herror T_remap(const Htuple hv_DictHandle)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(15,&ph);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&hv_DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_OpenvinoInfer(const Htuple Handle, const Htuple DictHandle)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(16,&ph);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&Handle);
  if (err == H_MSG_OK) err = HcStoreICT(ph,1,&DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_OpenvinoLoadModel(const Htuple DictHandle, Htuple *Handle)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(17,&ph);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&DictHandle);
  if (err == H_MSG_OK)
  {
    HcInitOCT(ph,0,Handle);
    err = HcCall(ph);
  }
  err = HcStoreOCT(ph,0,Handle,err);
  return HcPostCall(ph,err);
}

HUserExport Herror yolo_seg_detect(Hlong Handle, Hlong DictHandle)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(0,&ph);
  if (err == H_MSG_OK) HcStoreICL(ph,0,Handle);
  if (err == H_MSG_OK) HcStoreICL(ph,1,DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror cv_estimate_affine_partial2d(Hlong DictHandle)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(1,&ph);
  if (err == H_MSG_OK) HcStoreICL(ph,0,DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror cv_bf_knn_match(Hlong DictHandle)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(2,&ph);
  if (err == H_MSG_OK) HcStoreICL(ph,0,DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror cv_akaze_detect(Hlong DictHandle)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(3,&ph);
  if (err == H_MSG_OK) HcStoreICL(ph,0,DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror cv_orb_detect(Hlong DictHandle)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(4,&ph);
  if (err == H_MSG_OK) HcStoreICL(ph,0,DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror write_image_exif(const char *image_path, double latitude, double longitude, double altitude, double aperture, double shutter_speed, Hlong iso_number, double focal_length, const char *date_time, const char *camera_make, const char *camera_model)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(5,&ph);
  if (err == H_MSG_OK) HcStoreICSEnc(ph,0,image_path);
  if (err == H_MSG_OK) HcStoreICD(ph,1,latitude);
  if (err == H_MSG_OK) HcStoreICD(ph,2,longitude);
  if (err == H_MSG_OK) HcStoreICD(ph,3,altitude);
  if (err == H_MSG_OK) HcStoreICD(ph,4,aperture);
  if (err == H_MSG_OK) HcStoreICD(ph,5,shutter_speed);
  if (err == H_MSG_OK) HcStoreICL(ph,6,iso_number);
  if (err == H_MSG_OK) HcStoreICD(ph,7,focal_length);
  if (err == H_MSG_OK) HcStoreICSEnc(ph,8,date_time);
  if (err == H_MSG_OK) HcStoreICSEnc(ph,9,camera_make);
  if (err == H_MSG_OK) HcStoreICSEnc(ph,10,camera_model);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror CLAHE_image(const Hobject inimage, Hobject *outimage, Hlong k_width, Hlong k_height, Hlong clipLimit)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(6,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,inimage);
  if (err == H_MSG_OK) HcStoreICL(ph,0,k_width);
  if (err == H_MSG_OK) HcStoreICL(ph,1,k_height);
  if (err == H_MSG_OK) HcStoreICL(ph,2,clipLimit);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  err = HcStoreOO(ph,1,outimage,err);
  return HcPostCall(ph,err);
}

HUserExport Herror sub_A_roi(const Hobject smallimage, const Hobject bigimage, Hlong sy, Hlong sx, Hlong ew, Hlong eh)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(7,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,smallimage);
  if (err == H_MSG_OK) err = HcStoreIO(ph,2,bigimage);
  if (err == H_MSG_OK) HcStoreICL(ph,0,sy);
  if (err == H_MSG_OK) HcStoreICL(ph,1,sx);
  if (err == H_MSG_OK) HcStoreICL(ph,2,ew);
  if (err == H_MSG_OK) HcStoreICL(ph,3,eh);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror div_A_roi(const Hobject smallimage, const Hobject bigimage, Hlong sy, Hlong sx, Hlong ew, Hlong eh)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(8,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,smallimage);
  if (err == H_MSG_OK) err = HcStoreIO(ph,2,bigimage);
  if (err == H_MSG_OK) HcStoreICL(ph,0,sy);
  if (err == H_MSG_OK) HcStoreICL(ph,1,sx);
  if (err == H_MSG_OK) HcStoreICL(ph,2,ew);
  if (err == H_MSG_OK) HcStoreICL(ph,3,eh);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror div_B_roi(const Hobject smallimage, const Hobject bigimage, Hlong sy, Hlong sx, Hlong ew, Hlong eh)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(9,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,smallimage);
  if (err == H_MSG_OK) err = HcStoreIO(ph,2,bigimage);
  if (err == H_MSG_OK) HcStoreICL(ph,0,sy);
  if (err == H_MSG_OK) HcStoreICL(ph,1,sx);
  if (err == H_MSG_OK) HcStoreICL(ph,2,ew);
  if (err == H_MSG_OK) HcStoreICL(ph,3,eh);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror sub_B_roi(const Hobject smallimage, const Hobject bigimage, Hlong sy, Hlong sx, Hlong ew, Hlong eh)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(10,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,smallimage);
  if (err == H_MSG_OK) err = HcStoreIO(ph,2,bigimage);
  if (err == H_MSG_OK) HcStoreICL(ph,0,sy);
  if (err == H_MSG_OK) HcStoreICL(ph,1,sx);
  if (err == H_MSG_OK) HcStoreICL(ph,2,ew);
  if (err == H_MSG_OK) HcStoreICL(ph,3,eh);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror mul_roi(const Hobject smallimage, const Hobject bigimage, Hlong sy, Hlong sx, Hlong ew, Hlong eh)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(11,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,smallimage);
  if (err == H_MSG_OK) err = HcStoreIO(ph,2,bigimage);
  if (err == H_MSG_OK) HcStoreICL(ph,0,sy);
  if (err == H_MSG_OK) HcStoreICL(ph,1,sx);
  if (err == H_MSG_OK) HcStoreICL(ph,2,ew);
  if (err == H_MSG_OK) HcStoreICL(ph,3,eh);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror add_roi(const Hobject smallimage, const Hobject bigimage, Hlong sy, Hlong sx, Hlong ew, Hlong eh)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(12,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,smallimage);
  if (err == H_MSG_OK) err = HcStoreIO(ph,2,bigimage);
  if (err == H_MSG_OK) HcStoreICL(ph,0,sy);
  if (err == H_MSG_OK) HcStoreICL(ph,1,sx);
  if (err == H_MSG_OK) HcStoreICL(ph,2,ew);
  if (err == H_MSG_OK) HcStoreICL(ph,3,eh);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror PNGIn(const Hobject inimage, Hobject *outimage, Hlong acceleration)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(13,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,inimage);
  if (err == H_MSG_OK) HcStoreICL(ph,0,acceleration);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  err = HcStoreOO(ph,1,outimage,err);
  return HcPostCall(ph,err);
}

HUserExport Herror PNGOut(const Hobject inimage, Hobject *outimage)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(14,&ph);
  if (err == H_MSG_OK) err = HcStoreIO(ph,1,inimage);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  err = HcStoreOO(ph,1,outimage,err);
  return HcPostCall(ph,err);
}

HUserExport Herror remap(Hlong hv_DictHandle)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(15,&ph);
  if (err == H_MSG_OK) HcStoreICL(ph,0,hv_DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror OpenvinoInfer(Hlong Handle, Hlong DictHandle)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(16,&ph);
  if (err == H_MSG_OK) HcStoreICL(ph,0,Handle);
  if (err == H_MSG_OK) HcStoreICL(ph,1,DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror OpenvinoLoadModel(Hlong DictHandle, Hlong *Handle)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(17,&ph);
  if (err == H_MSG_OK) HcStoreICL(ph,0,DictHandle);
  if (err == H_MSG_OK)
  {
    HcInitOCL(ph,0);
    err = HcCall(ph);
  }
  err = HcStoreOCL(ph,0,Handle,err);
  return HcPostCall(ph,err);
}

